name: flutter_table_plus
description: "A highly customizable and efficient table widget for Flutter, featuring synchronized scrolling, theming, sorting, selection, column reordering, hover buttons, and expandable rows."
version: 2.3.3
homepage: https://github.com/kihyun1998/flutter_table_plus
repository: https://github.com/kihyun1998/flutter_table_plus
topics:
  - table
  - datatable
  - data-table
  - grid
  - datagrid

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
